### ISSUE TITLE
Connected device does not support API version requested by app.

### ISSUE THREAD

**Issue by amunizp** [bingtimren/fitbit-sim-starter#13]
* **I'm submitting a ...**
[X ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
I installed they system using 
$sudo apt install docker.io
$sudo npx fitbit-sim-starter

connected to online account. Noticed the fan running as described. 

Run well, chose Sense. Simulator seemed to connect but got error when attempting to run the code:
[12:03:43]Sideload of app failed. Connected device does not support API version requested by app.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

API version in docker needs to be upgraded? How do I do that?

**Comment by amunizp** [comment]
![Screenshot from 2022-06-04 12-04-10](https://user-images.githubusercontent.com/5783911/171996658-c6dce271-0011-472f-9cc2-a75aa069effb.png)
[simulator-output.txt](https://github.com/bingtimren/fitbit-sim-starter/files/8837553/simulator-output.txt)
Adding extra debug info of the command line output and screenshot.

**Comment by amunizp** [comment]
![Screenshot from 2022-06-04 12-04-10](https://user-images.githubusercontent.com/5783911/171996838-f9bb7241-81f2-43b1-a1d9-557e7a1fd263.png)
[simulator-output.txt](https://github.com/bingtimren/fitbit-sim-starter/files/8837560/simulator-output.txt)
Command line output and screenshot of simulator.

**Comment by bingtimren** [comment]
This doesn't feel like an issue of the image or the starter, as the error was reported by the simulator. 

All I can do is to try to upgrade the simulator version. However my attempt to upgrade it to 0.9.4 just failed. It could show the login page, but after that it could not load the simulator.

Maybe try a different device type to load your app?

**Comment by bingtimren** [comment]
Ok, I just solved the problem and upgraded the image to the latest simulator version 0.9.4. 

Now try starting the simulator with command `fitbit-sim-starter -u -r`. Hope it solves your issue.
