### ISSUE TITLE
Enable --network=host in all the cases (or add an option for it)

### ISSUE THREAD

**Issue by 3v1n0** [bingtimren/fitbit-sim-starter#3]
I'm developing an app requiring a companion android application, so in order to develop it the watch app needs to connect to a localhost server to exchange data.

Having the simulator in the same network of the host easily allows to use 127.0.0.1 to connect to the app (especially when you can use `adb forward tcp:XXXX tcp:XXX` to make the app port from device/simulator in localhost as well).

**Comment by bingtimren** [comment]
Just released a new version 1.0.13 with an option to pass whatever options to docker when creating the container.

`  -o, --container-opts <options>  additional options for the container (default: "")`

For example you can have the container in the host network and limit its CPU usage (I'm trying to reduce the annoying CPU fan noise but it also slows down the simulator unfortunately). 

`npx fitbit-sim-starter --container-opts="--network=host --cpus=1" `

**Comment by 3v1n0** [comment]
Great!

FWIW, the higher CPU usage is actually only happening when no app is running in the simulator here, so not really a big deal... And I've been able to upgrade to simulator v9 (for new devices with SDK5).

But all still using the the previous image version (based on 8.2) otherwise with the latest one I'm getting a black screen...

Out of curiosity, do you have the settings page working for you? As that is always empty here (not sure if it worked in previous revisions).

**Comment by bingtimren** [comment]
I have also upgraded the simulator. Use "-u" to upgrade docker image to simulator v9.

Yes, setting page works without issue here. Did you try your setting page on your phone? Also try the image I built and see if setting page works with that image.

![Screenshot from 2020-10-21 19-43-31](https://user-images.githubusercontent.com/2824513/96695836-d5bfa300-13d5-11eb-9659-87bed8db7992.png)

**Comment by 3v1n0** [comment]
I've tested also [fitbit-terminal](https://github.com/jdhartley/terminal-for-fitbit) and I just get a blank page in the simulator:

![image](https://user-images.githubusercontent.com/345675/96712933-261c0e00-13a0-11eb-84fc-76767b97f4d2.png)

**Comment by 3v1n0** [comment]
And... Using latest image to me is just a black page:

Moving to https://github.com/bingtimren/fitbit-simulator-linux-wine-image/issues/1
